# symbols.py — NSE Stock Universe

FNO_STOCKS = [
    "RELIANCE","TCS","HDFCBANK","INFY","ICICIBANK","HINDUNILVR","ITC","SBIN","BHARTIARTL","KOTAKBANK",
    "LT","AXISBANK","ASIANPAINT","MARUTI","TITAN","NESTLEIND","HCLTECH","SUNPHARMA","BAJFINANCE","WIPRO",
    "ULTRACEMCO","ONGC","NTPC","POWERGRID","TATAMOTORS","TECHM","HINDALCO","TATASTEEL","JSWSTEEL","ADANIENT",
    "ADANIPORTS","COALINDIA","BPCL","IOC","DRREDDY","DIVISLAB","CIPLA","APOLLOHOSP","BAJAJFINSV","EICHERMOT",
    "BRITANNIA","HEROMOTOCO","GRASIM","SHREECEM","UPL","PIDILITIND","SIEMENS","HAVELLS","BERGEPAINT","MARICO",
    "DABUR","GODREJCP","COLPAL","MCDOWELL-N","JUBLFOOD","TATACONSUM","INDUSINDBK","FEDERALBNK","IDFCFIRSTB",
    "PNB","BANKBARODA","CANBK","UNIONBANK","RBLBANK","BANDHANBNK","AUBANK","NAUKRI","IRCTC","DMART",
    "ZOMATO","PAYTM","NYKAA","POLICYBZR","CARTRADE","INDIAMART","MPHASIS","COFORGE","PERSISTENT","LTIM",
    "LTTS","TATAELXSI","KPITTECH","SONACOMS","SUVENPHAR","AUROPHARMA","BIOCON","TORNTPHARM","ALKEM","IPCALAB",
    "LALPATHLAB","METROPOLIS","MAXHEALTH","FORTIS","NH","CONCOR","GMRAIRPORT","IRFC","RVNL","RAILTEL",
    "CESC","TATAPOWER","ADANIGREEN","ADANITRANS","TORNTPOWER","CUMMINSIND","THERMAX","ABB","BHEL","BEML",
    "BEL","HAL","MOTHERSON","BOSCHLTD","ESCORTS","TIINDIA","VARROC","MINDAIND","AMARAJABAT","EXIDEIND",
    "M&M","M&MFIN","MAHINDCIE","CHOLAFIN","MUTHOOTFIN","BAJAJHLDNG","SRTRANSFIN","PEL","MANAPPURAM",
    "HDFCLIFE","SBILIFE","ICICIlombard","ICICIGI","NIACL","STARHEALTH","GICRE","LICHSGFIN","CANFINHOME",
    "PNBHOUSING","AAVAS","REPCO","GRUH","HOMEFIRST","APTUS","UJJIVANSFB","EQUITASBNK","SURYODAY",
    "ABCAPITAL","EDELWEISS","MOTILALOFS","ANGELONE","5PAISA","CDSL","BSE","MCX","IEX","CAMS",
    "L&TFH","RECLTD","PFC","IREDA","NHPC","SJVN","GMDC","NMDC","MOIL","NATIONALUM",
    "HINDCOPPER","VEDL","SAIL","RATNAMANI","APL","RAMCOCEM","JKCEMENT","DALBHARAT","HEIDELBERG","BIRLACORPN",
    "SRF","ATUL","DEEPAKNI","CLEAN","FINEORG","SUDARSCHEM","NAVINFLUOR","ALKYLAMINE","BALRAMCHIN","RENUKA",
    "DHAMPUR","EID","TRIVENI","PRAJIND","ARE&M","POLYCAB","KEI","FINOLEX","HBLPOWER","SCHNEIDER",
    "VOLTAS","BLUESTAR","WHIRLPOOL","CROMPTON","ORIENTELEC","RAJESHEXPO","TITAN","KALYAN","SENCO",
    "PCJEWELLER","TRIBHOVANDAS","KFINTECH","COMPUTER AGE","MFSL","IIFL","IIFLWAM","360ONE","GEOJITFSL",
]

# Remove duplicates while preserving order
_seen = set()
FNO_STOCKS = [x for x in FNO_STOCKS if not (x in _seen or _seen.add(x))]

ALL_STOCKS = FNO_STOCKS + [
    "ZYDUSLIFE","GLAND","GRANULES","SYNGENE","NEULANDLAB","SEQUENT","VIMTALABS","PANACEA","STRIDES",
    "JBCHEPHARM","SOLARA","LAURUSLABS","SHILPAMED","POLYMED","NUVOCO","JKPAPER","WSTCSTPAPR",
    "TIMETECHNO","ROUTE","SWSOLAR","WEBSOL","INOXWIND","SUZLON","RPOWER","MPSLTD","ONWARDTEC",
    "SAKSOFT","TANLA","INTELLECT","NEWGEN","NUCLEUS","MASTEK","DATAPATTERNSIND","ZENSAR","CYIENT",
    "ELGIEQUIP","GRINDWELL","KENNAMETAL","LAKSHMINH","TEXMACO","TITAGARH","IRCON","NBCC","WABCO",
    "SPARC","NATCOPHARM","AJANTAPHARM","JB","CAPLIPOINT","GLAXO","PFIZER","ABBOTINDIA","NOVARTIS",
    "SANOFI","WOCKPHARMA","ERIS","RPG","GPPL","VIRINCHI","HERANBA","BIOPHARMA","JSWENERGY",
    "GREENPANEL","CENTURY","CENTURYPLY","GREENPLY","ACTION","WONDERLA","INDHOTEL","CHALET","EIH",
    "LEMON TREE","MAHINDRAHOLIDAY","MHRIL","THOMASCOOK","COX&KINGS","YATHARTH","KRISHNAHOTEL",
    "DIXON","AMBER","PG ELECTROPLAST","SYRMA","AVALON","KAYNES","IDEAFORGE","PARAS","DELHIVERY",
    "BLUEDART","GATI","VRL","TCI","MAHINDRALOG","ALLCARGO","GATEWAY","CONTAINERWAY","ESAB",
    "GRAPHITE","HEG","ISGEC","ELECON","GREAVES","MMTC","PTC","NHPC","IGPL","NXTDIGITAL",
]

_seen2 = set()
ALL_STOCKS = [x for x in ALL_STOCKS if not (x in _seen2 or _seen2.add(x))]
FNO_SET = set(FNO_STOCKS)
